"""Dataset persistence for v2 offline datasets.

Saves and loads trajectory / flattened datasets generated by DataGenerator.
Each saved dataset includes a manifest with generation metadata for
reproducibility traceability.

Directory layout::

    <dataset_dir>/
        trajectory.npz       # {s_endo_0, z_path, z_fork}   (optional)
        flat.npz             # {s_endo, z, z_next_main, z_next_fork}  (optional)
        manifest.json        # env config, seed, shapes, creation time

Usage::

    from src.v2.data.storage import save_dataset, load_dataset

    # Save after generation:
    save_dataset(traj_data, path="outputs/datasets/basic/seed_20_26",
                 fmt="trajectory", env_config={"theta": 0.7, ...})

    # Reload later:
    data = load_dataset("outputs/datasets/basic/seed_20_26", fmt="trajectory")
"""

import json
import os
from datetime import datetime, timezone
from typing import Optional

import numpy as np
import tensorflow as tf


def save_dataset(
    data: dict,
    path: str,
    fmt: str,
    env_config: Optional[dict] = None,
    generator_config: Optional[dict] = None,
) -> str:
    """Save a dataset dict to disk with a manifest.

    Args:
        data:             Dict of tensors/arrays (keys depend on fmt).
        path:             Directory to save into.
        fmt:              "trajectory" or "flat" — determines filename.
        env_config:       Optional environment config dict for manifest.
        generator_config: Optional DataGeneratorConfig dict for manifest.

    Returns:
        The path (for convenience).
    """
    os.makedirs(path, exist_ok=True)

    filename = {"trajectory": "trajectory.npz", "flat": "flat.npz"}
    if fmt not in filename:
        raise ValueError(f"fmt must be 'trajectory' or 'flat', got '{fmt}'")

    # Convert tensors to numpy
    arrays = {}
    shapes = {}
    for k, v in data.items():
        arr = v.numpy() if isinstance(v, tf.Tensor) else np.asarray(v)
        arrays[k] = arr
        shapes[k] = list(arr.shape)

    np.savez(os.path.join(path, filename[fmt]), **arrays)

    # Manifest (append/update — don't overwrite if both formats saved)
    manifest_path = os.path.join(path, "manifest.json")
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            manifest = json.load(f)
    else:
        manifest = {}

    manifest[fmt] = {
        "keys": list(arrays.keys()),
        "shapes": shapes,
        "saved_at": datetime.now(timezone.utc).isoformat(),
    }
    if env_config is not None:
        manifest["env_config"] = env_config
    if generator_config is not None:
        manifest["generator_config"] = generator_config

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, default=str)

    return path


def load_dataset(path: str, fmt: str) -> dict:
    """Load a dataset dict from disk.

    Args:
        path: Directory containing the saved dataset.
        fmt:  "trajectory" or "flat".

    Returns:
        Dict of tf.Tensor values.

    Raises:
        FileNotFoundError: if the expected .npz file is missing.
    """
    filename = {"trajectory": "trajectory.npz", "flat": "flat.npz"}
    if fmt not in filename:
        raise ValueError(f"fmt must be 'trajectory' or 'flat', got '{fmt}'")

    npz_path = os.path.join(path, filename[fmt])
    if not os.path.exists(npz_path):
        raise FileNotFoundError(
            f"No {filename[fmt]} found at {path}. "
            f"Available files: {os.listdir(path)}")

    npz = np.load(npz_path)
    return {k: tf.constant(npz[k]) for k in npz.files}


def load_manifest(path: str) -> dict:
    """Load the manifest for a saved dataset directory.

    Args:
        path: Directory containing manifest.json.

    Returns:
        Manifest dict with keys per saved format plus env_config.
    """
    manifest_path = os.path.join(path, "manifest.json")
    if not os.path.exists(manifest_path):
        raise FileNotFoundError(f"No manifest.json found at {path}")
    with open(manifest_path) as f:
        return json.load(f)
